
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixedMain;

	private global::Gtk.Button btnHello;

	private global::Gtk.Entry entryName;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.DefaultWidth = 300;
		this.DefaultHeight = 250;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixedMain = new global::Gtk.Fixed();
		this.fixedMain.Name = "fixedMain";
		this.fixedMain.HasWindow = false;
		// Container child fixedMain.Gtk.Fixed+FixedChild
		this.btnHello = new global::Gtk.Button();
		this.btnHello.CanFocus = true;
		this.btnHello.Name = "btnHello";
		this.btnHello.UseUnderline = true;
		this.btnHello.Label = global::Mono.Unix.Catalog.GetString("Hello");
		this.fixedMain.Add(this.btnHello);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixedMain[this.btnHello]));
		w1.X = 142;
		w1.Y = 86;
		// Container child fixedMain.Gtk.Fixed+FixedChild
		this.entryName = new global::Gtk.Entry();
		this.entryName.CanFocus = true;
		this.entryName.Name = "entryName";
		this.entryName.IsEditable = true;
		this.entryName.InvisibleChar = '●';
		this.fixedMain.Add(this.entryName);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixedMain[this.entryName]));
		w2.X = 80;
		w2.Y = 48;
		this.Add(this.fixedMain);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnHello.Clicked += new global::System.EventHandler(this.OnBtnHelloClicked);
	}
}
